### PR TITLE
Secretly depends on plugins that are hard to notice.

### PR DESCRIPTION
**Pull request by Endermanbugzjfc**
Please add the dependencies into plugin.yml to shorten the time of setting up this plugin.

### CODE REVIEW

**Comment by GabBiswajit** [comment]
Umm

**Comment by GabBiswajit** [comment]
It's not required player can use any multi world Plugin.

**Comment by Endermanbugzjfc** [comment]
Note: the `void` Generator requires MW, they would have to re-upload a world if they don't have MW.

**Comment by GabBiswajit** [comment]
I know about that

**Comment by GabBiswajit** [comment]
Thanks For Help !

**Comment by GabBiswajit** [comment]
AnyMore Think Which In This Plugin?

**Pull request closed without merging**
